# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r:
- oldrel
- release
- devel
os:
- linux
- osx
jobs:
  exclude:
  # macOS binary packages not available for r-devel
  - r: devel
    os: osx
after_success:
# tests in the package change some environment variables
# reinstall needed packages
- Rscript -e 'if (!require("tinytex")) install.packages("tinytex"); tinytex::install_tinytex()'
- Rscript -e 'if (!require("covr")) install.packages("covr")'
- Rscript -e 'if (!require("pkgdown")) install.packages("pkgdown")'
- Rscript -e 'if (!require("remotes")) install.packages("remotes")'
- Rscript -e 'if (!require("jeksterslabRterm")) remotes::install_github("jeksterslabds/jeksterslabRterm")'
- Rscript -e 'covr::codecov()'
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip_cleanup: true
  strategy: git
  token: "$GITHUB_PAT"
  keep_history: true
  local_dir: docs
  on:
    branch: master
