# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r:
- oldrel
- release
- devel
os:
- linux
- osx
jobs:
  exclude:
  # macOS binary packages not available for r-devel
  - r: devel
    os: osx
after_success:
# tests in the package change some environment variables
# reinstall needed packages
- Rscript -e 'if (!require("covr")) install.packages("covr")'
- Rscript -e 'covr::codecov()'
